version: '3'
services:
  jazapi:
    build: ./jaz-api
    restart: on-failure:5
    ports:
    - "11111:11111"
  jazclient:
    build: ./jaz-client
    ports:
    - "22222:22222"
  cardb:
    build: ./db
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: carseller
      MYSQL_USER: sales_prog
      MYSQL_PASSWORD: prog_pwd